CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AuditLogSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "UserId" uuid,
        "Method" text NOT NULL,
        "Path" text NOT NULL,
        "StatusCode" integer NOT NULL,
        "IpAddress" text,
        "DurationMs" bigint NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_AuditLogSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "CompanyProfileSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "LegalName" text NOT NULL,
        "CurrencyCode" text NOT NULL,
        "DefaultPayDay" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_CompanyProfileSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "EmployeeSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Email" text NOT NULL,
        "JobTitle" text NOT NULL,
        "BaseSalary" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_EmployeeSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "PayrollPeriodSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "Status" integer NOT NULL,
        "PeriodStartDate" date NOT NULL,
        "PeriodEndDate" date NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollPeriodSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "TenantSet" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Slug" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_TenantSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_CompanyProfileSet_TenantId" ON "CompanyProfileSet" ("TenantId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE INDEX "IX_EmployeeSet_TenantId_Email" ON "EmployeeSet" ("TenantId", "Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_TenantSet_Slug" ON "TenantSet" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215225418_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260215225418_InitialCreate', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215231909_AddAttendanceInputs') THEN
    CREATE TABLE "AttendanceInputSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "DaysPresent" integer NOT NULL,
        "DaysAbsent" integer NOT NULL,
        "OvertimeHours" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_AttendanceInputSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215231909_AddAttendanceInputs') THEN
    CREATE UNIQUE INDEX "IX_AttendanceInputSet_TenantId_EmployeeId_Year_Month" ON "AttendanceInputSet" ("TenantId", "EmployeeId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215231909_AddAttendanceInputs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260215231909_AddAttendanceInputs', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE TABLE "PayrollAdjustmentSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "Type" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Notes" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollAdjustmentSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE TABLE "PayrollLineSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PayrollRunId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "BaseSalary" numeric NOT NULL,
        "Allowances" numeric NOT NULL,
        "Deductions" numeric NOT NULL,
        "OvertimeHours" numeric NOT NULL,
        "OvertimeAmount" numeric NOT NULL,
        "NetAmount" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollLineSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE TABLE "PayrollRunSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PayrollPeriodId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "CalculatedAtUtc" timestamp with time zone,
        "ApprovedAtUtc" timestamp with time zone,
        "LockedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollRunSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE UNIQUE INDEX "IX_PayrollPeriodSet_TenantId_Year_Month" ON "PayrollPeriodSet" ("TenantId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE INDEX "IX_PayrollAdjustmentSet_TenantId_EmployeeId_Year_Month_Type" ON "PayrollAdjustmentSet" ("TenantId", "EmployeeId", "Year", "Month", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE UNIQUE INDEX "IX_PayrollLineSet_TenantId_PayrollRunId_EmployeeId" ON "PayrollLineSet" ("TenantId", "PayrollRunId", "EmployeeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    CREATE INDEX "IX_PayrollRunSet_TenantId_PayrollPeriodId" ON "PayrollRunSet" ("TenantId", "PayrollPeriodId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260215232603_AddPayrollEngineV1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260215232603_AddPayrollEngineV1', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216203820_AddExportArtifacts') THEN
    CREATE TABLE "ExportArtifactSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PayrollRunId" uuid NOT NULL,
        "EmployeeId" uuid,
        "ArtifactType" text NOT NULL,
        "FileName" text NOT NULL,
        "ContentType" text NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "CreatedByUserId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ExportArtifactSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216203820_AddExportArtifacts') THEN
    CREATE INDEX "IX_ExportArtifactSet_TenantId_PayrollRunId_CreatedAtUtc" ON "ExportArtifactSet" ("TenantId", "PayrollRunId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260216203820_AddExportArtifacts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260216203820_AddExportArtifacts', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    ALTER TABLE "ExportArtifactSet" ADD "CompletedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    ALTER TABLE "ExportArtifactSet" ADD "ErrorMessage" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    ALTER TABLE "ExportArtifactSet" ADD "FileData" bytea;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    ALTER TABLE "ExportArtifactSet" ADD "Status" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    CREATE INDEX "IX_ExportArtifactSet_TenantId_Status_CreatedAtUtc" ON "ExportArtifactSet" ("TenantId", "Status", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220130340_AddAsyncExportJobFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220130340_AddAsyncExportJobFields', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220162517_AddLeaveManagementV1') THEN
    CREATE TABLE "LeaveBalanceSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "LeaveType" integer NOT NULL,
        "AllocatedDays" numeric NOT NULL,
        "UsedDays" numeric NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LeaveBalanceSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220162517_AddLeaveManagementV1') THEN
    CREATE TABLE "LeaveRequestSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "LeaveType" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "TotalDays" numeric NOT NULL,
        "Reason" text NOT NULL,
        "Status" integer NOT NULL,
        "RejectionReason" text,
        "ReviewedByUserId" uuid,
        "ReviewedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_LeaveRequestSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220162517_AddLeaveManagementV1') THEN
    CREATE UNIQUE INDEX "IX_LeaveBalanceSet_TenantId_EmployeeId_Year_LeaveType" ON "LeaveBalanceSet" ("TenantId", "EmployeeId", "Year", "LeaveType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220162517_AddLeaveManagementV1') THEN
    CREATE INDEX "IX_LeaveRequestSet_TenantId_EmployeeId_StartDate_EndDate" ON "LeaveRequestSet" ("TenantId", "EmployeeId", "StartDate", "EndDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220162517_AddLeaveManagementV1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220162517_AddLeaveManagementV1', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220170655_AddUnpaidLeavePayrollBreakdown') THEN
    ALTER TABLE "PayrollLineSet" ADD "ManualDeductions" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220170655_AddUnpaidLeavePayrollBreakdown') THEN
    ALTER TABLE "PayrollLineSet" ADD "UnpaidLeaveDays" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220170655_AddUnpaidLeavePayrollBreakdown') THEN
    ALTER TABLE "PayrollLineSet" ADD "UnpaidLeaveDeduction" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220170655_AddUnpaidLeavePayrollBreakdown') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220170655_AddUnpaidLeavePayrollBreakdown', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "PayrollLineSet" ADD "GosiEmployeeContribution" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "PayrollLineSet" ADD "GosiEmployerContribution" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "PayrollLineSet" ADD "GosiWageBase" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "EmployeeSet" ADD "GosiBasicWage" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "EmployeeSet" ADD "GosiHousingAllowance" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "EmployeeSet" ADD "IsGosiEligible" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    ALTER TABLE "EmployeeSet" ADD "IsSaudiNational" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220215558_AddGosiV1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220215558_AddGosiV1', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224217_AddEosV1AndEmployeeStartDate') THEN
    ALTER TABLE "EmployeeSet" ADD "StartDate" date NOT NULL DEFAULT DATE '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224217_AddEosV1AndEmployeeStartDate') THEN
    ALTER TABLE "CompanyProfileSet" ADD "EosAfterFiveYearsMonthFactor" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224217_AddEosV1AndEmployeeStartDate') THEN
    ALTER TABLE "CompanyProfileSet" ADD "EosFirstFiveYearsMonthFactor" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224217_AddEosV1AndEmployeeStartDate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220224217_AddEosV1AndEmployeeStartDate', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224925_BackfillEosDefaults') THEN
    ALTER TABLE "CompanyProfileSet"
    ALTER COLUMN "EosFirstFiveYearsMonthFactor" SET DEFAULT 0.5;
    ALTER TABLE "CompanyProfileSet"
    ALTER COLUMN "EosAfterFiveYearsMonthFactor" SET DEFAULT 1.0;
    UPDATE "CompanyProfileSet"
    SET "EosFirstFiveYearsMonthFactor" = 0.5
    WHERE "EosFirstFiveYearsMonthFactor" = 0;
    UPDATE "CompanyProfileSet"
    SET "EosAfterFiveYearsMonthFactor" = 1.0
    WHERE "EosAfterFiveYearsMonthFactor" = 0;
    UPDATE "EmployeeSet"
    SET "StartDate" = "CreatedAtUtc"::date
    WHERE "StartDate" = '-infinity'::date OR "StartDate" < DATE '1900-01-01';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220224925_BackfillEosDefaults') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220224925_BackfillEosDefaults', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220231752_AddExportMetadataJson') THEN
    ALTER TABLE "ExportArtifactSet" ADD "MetadataJson" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260220231752_AddExportMetadataJson') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260220231752_AddExportMetadataJson', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "EmployeeSet" ADD "BankIban" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "EmployeeSet" ADD "BankName" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "EmployeeSet" ADD "EmployeeNumber" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "CompanyProfileSet" ADD "WpsCompanyBankCode" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "CompanyProfileSet" ADD "WpsCompanyBankName" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    ALTER TABLE "CompanyProfileSet" ADD "WpsCompanyIban" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221083138_AddWpsConfigurationFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221083138_AddWpsConfigurationFields', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221114500_AddKsaComplianceFields') THEN
    ALTER TABLE "EmployeeSet" ADD "IqamaNumber" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221114500_AddKsaComplianceFields') THEN
    ALTER TABLE "EmployeeSet" ADD "IqamaExpiryDate" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221114500_AddKsaComplianceFields') THEN
    ALTER TABLE "EmployeeSet" ADD "WorkPermitExpiryDate" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221114500_AddKsaComplianceFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221114500_AddKsaComplianceFields', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221131436_AddComplianceScoreSnapshots') THEN
    CREATE TABLE "ComplianceScoreSnapshotSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "SnapshotDate" date NOT NULL,
        "Score" integer NOT NULL,
        "Grade" text NOT NULL,
        "SaudizationPercent" numeric NOT NULL,
        "WpsCompanyReady" boolean NOT NULL,
        "EmployeesMissingPaymentData" integer NOT NULL,
        "CriticalAlerts" integer NOT NULL,
        "WarningAlerts" integer NOT NULL,
        "NoticeAlerts" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplianceScoreSnapshotSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221131436_AddComplianceScoreSnapshots') THEN
    CREATE UNIQUE INDEX "IX_ComplianceScoreSnapshotSet_TenantId_SnapshotDate" ON "ComplianceScoreSnapshotSet" ("TenantId", "SnapshotDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221131436_AddComplianceScoreSnapshots') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221131436_AddComplianceScoreSnapshots', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    ALTER TABLE "CompanyProfileSet" ADD "ComplianceDigestEmail" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    ALTER TABLE "CompanyProfileSet" ADD "ComplianceDigestEnabled" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    ALTER TABLE "CompanyProfileSet" ADD "ComplianceDigestFrequency" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    ALTER TABLE "CompanyProfileSet" ADD "ComplianceDigestHourUtc" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    ALTER TABLE "CompanyProfileSet" ADD "LastComplianceDigestSentAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221133200_AddComplianceDigestSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221133200_AddComplianceDigestSettings', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140000_AddComplianceAlerts') THEN
    CREATE TABLE "ComplianceAlertSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "EmployeeName" text NOT NULL,
        "IsSaudiNational" boolean NOT NULL,
        "DocumentType" text NOT NULL,
        "DocumentNumber" text NOT NULL,
        "ExpiryDate" date NOT NULL,
        "DaysLeft" integer NOT NULL,
        "Severity" text NOT NULL,
        "IsResolved" boolean NOT NULL,
        "ResolveReason" text NOT NULL,
        "ResolvedByUserId" uuid,
        "ResolvedAtUtc" timestamp with time zone,
        "LastDetectedAtUtc" timestamp with time zone NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplianceAlertSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140000_AddComplianceAlerts') THEN
    CREATE UNIQUE INDEX "IX_ComplianceAlertSet_TenantId_EmployeeId_DocumentType_ExpiryDate" ON "ComplianceAlertSet" ("TenantId", "EmployeeId", "DocumentType", "ExpiryDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140000_AddComplianceAlerts') THEN
    CREATE INDEX "IX_ComplianceAlertSet_TenantId_IsResolved_DaysLeft" ON "ComplianceAlertSet" ("TenantId", "IsResolved", "DaysLeft");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140000_AddComplianceAlerts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221140000_AddComplianceAlerts', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140722_AddComplianceDigestDeliveries') THEN
    CREATE TABLE "ComplianceDigestDeliverySet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RetryOfDeliveryId" uuid,
        "RecipientEmail" text NOT NULL,
        "Subject" text NOT NULL,
        "TriggerType" text NOT NULL,
        "Frequency" text NOT NULL,
        "Status" text NOT NULL,
        "Simulated" boolean NOT NULL,
        "ErrorMessage" text NOT NULL,
        "Score" integer NOT NULL,
        "Grade" text NOT NULL,
        "SentAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplianceDigestDeliverySet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140722_AddComplianceDigestDeliveries') THEN
    CREATE INDEX "IX_ComplianceDigestDeliverySet_TenantId_CreatedAtUtc" ON "ComplianceDigestDeliverySet" ("TenantId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140722_AddComplianceDigestDeliveries') THEN
    CREATE INDEX "IX_ComplianceDigestDeliverySet_TenantId_Status_CreatedAtUtc" ON "ComplianceDigestDeliverySet" ("TenantId", "Status", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260221140722_AddComplianceDigestDeliveries') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260221140722_AddComplianceDigestDeliveries', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260225132503_AddEmployeeContractEndDate') THEN
    ALTER TABLE "EmployeeSet" ADD "ContractEndDate" date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260225132503_AddEmployeeContractEndDate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260225132503_AddEmployeeContractEndDate', '8.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    ALTER TABLE "PayrollLineSet" ADD "LoanDeduction" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    ALTER TABLE "EmployeeSet" ADD "GradeCode" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    ALTER TABLE "EmployeeSet" ADD "LocationCode" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "AllowancePolicyMatrixSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PolicyName" text NOT NULL,
        "GradeCode" text NOT NULL,
        "LocationCode" text NOT NULL,
        "HousingAmount" numeric NOT NULL,
        "TransportAmount" numeric NOT NULL,
        "MealAmount" numeric NOT NULL,
        "ProrationMethod" text NOT NULL,
        "EffectiveFrom" date NOT NULL,
        "EffectiveTo" date,
        "IsTaxable" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_AllowancePolicyMatrixSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "AllowancePolicySet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PolicyName" text NOT NULL,
        "JobTitle" text NOT NULL,
        "MonthlyAmount" numeric NOT NULL,
        "EffectiveFrom" date NOT NULL,
        "EffectiveTo" date,
        "IsTaxable" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_AllowancePolicySet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "ComplianceRuleEventSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RuleId" uuid NOT NULL,
        "EmployeeId" uuid,
        "EntityType" text NOT NULL,
        "EntityId" uuid,
        "Status" text NOT NULL,
        "TriggeredAtUtc" timestamp with time zone NOT NULL,
        "ResolvedAtUtc" timestamp with time zone,
        "Message" text NOT NULL,
        "MetadataJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplianceRuleEventSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "ComplianceRuleSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RuleCode" text NOT NULL,
        "RuleName" text NOT NULL,
        "RuleCategory" text NOT NULL,
        "RuleConfigJson" text NOT NULL,
        "Severity" text NOT NULL,
        "IsEnabled" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ComplianceRuleSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "DataQualityFixBatchSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "BatchReference" text NOT NULL,
        "TriggeredByUserId" uuid,
        "TotalItems" integer NOT NULL,
        "SuccessItems" integer NOT NULL,
        "FailedItems" integer NOT NULL,
        "Status" text NOT NULL,
        "ResultJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_DataQualityFixBatchSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "DataQualityIssueSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "IssueCode" text NOT NULL,
        "Severity" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" uuid,
        "IssueStatus" text NOT NULL,
        "IssueMessage" text NOT NULL,
        "FixActionCode" text NOT NULL,
        "FixPayloadJson" text NOT NULL,
        "DetectedAtUtc" timestamp with time zone NOT NULL,
        "ResolvedAtUtc" timestamp with time zone,
        "ResolvedByUserId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_DataQualityIssueSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "EmployeeLoanInstallmentSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeLoanId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "Year" integer NOT NULL,
        "Month" integer NOT NULL,
        "Amount" numeric NOT NULL,
        "Status" text NOT NULL,
        "PayrollRunId" uuid,
        "DeductedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_EmployeeLoanInstallmentSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "EmployeeLoanSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "LoanType" text NOT NULL,
        "PrincipalAmount" numeric NOT NULL,
        "RemainingBalance" numeric NOT NULL,
        "InstallmentAmount" numeric NOT NULL,
        "StartYear" integer NOT NULL,
        "StartMonth" integer NOT NULL,
        "TotalInstallments" integer NOT NULL,
        "PaidInstallments" integer NOT NULL,
        "Status" text NOT NULL,
        "Notes" text NOT NULL,
        "CreatedByUserId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_EmployeeLoanSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "EmployeeOffboardingSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "EffectiveDate" date NOT NULL,
        "Reason" text NOT NULL,
        "Status" text NOT NULL,
        "RequestedByUserId" uuid,
        "ApprovedByUserId" uuid,
        "ApprovedAtUtc" timestamp with time zone,
        "PaidAtUtc" timestamp with time zone,
        "ClosedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_EmployeeOffboardingSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "EmployeeSelfServiceRequestSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "RequestType" text NOT NULL,
        "Status" text NOT NULL,
        "PayloadJson" text NOT NULL,
        "ReviewerUserId" uuid,
        "ReviewedAtUtc" timestamp with time zone,
        "ResolutionNotes" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_EmployeeSelfServiceRequestSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "IntegrationSyncJobSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Provider" text NOT NULL,
        "Operation" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" uuid,
        "IdempotencyKey" text NOT NULL,
        "RequestPayloadJson" text NOT NULL,
        "ResponsePayloadJson" text NOT NULL,
        "Status" text NOT NULL,
        "AttemptCount" integer NOT NULL,
        "MaxAttempts" integer NOT NULL,
        "NextAttemptAtUtc" timestamp with time zone NOT NULL,
        "LastAttemptAtUtc" timestamp with time zone,
        "StartedAtUtc" timestamp with time zone,
        "CompletedAtUtc" timestamp with time zone,
        "DeadlineAtUtc" timestamp with time zone,
        "LastError" text NOT NULL,
        "ExternalReference" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_IntegrationSyncJobSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "NotificationQueueSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RecipientType" text NOT NULL,
        "RecipientValue" text NOT NULL,
        "Channel" text NOT NULL,
        "TemplateCode" text NOT NULL,
        "RelatedEntityType" text NOT NULL,
        "RelatedEntityId" uuid,
        "PayloadJson" text NOT NULL,
        "Status" text NOT NULL,
        "ScheduledAtUtc" timestamp with time zone NOT NULL,
        "SentAtUtc" timestamp with time zone,
        "ProviderMessageId" text NOT NULL,
        "ErrorMessage" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_NotificationQueueSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "NotificationTemplateSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "TemplateCode" text NOT NULL,
        "Channel" text NOT NULL,
        "Subject" text NOT NULL,
        "Body" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_NotificationTemplateSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "OffboardingChecklistApprovalSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ChecklistItemId" uuid NOT NULL,
        "Status" text NOT NULL,
        "RequestedByUserId" uuid,
        "RequestedAtUtc" timestamp with time zone,
        "ApprovedByUserId" uuid,
        "ApprovedAtUtc" timestamp with time zone,
        "Notes" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OffboardingChecklistApprovalSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "OffboardingChecklistItemSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ChecklistId" uuid NOT NULL,
        "ItemCode" text NOT NULL,
        "ItemLabel" text NOT NULL,
        "Status" text NOT NULL,
        "CompletedAtUtc" timestamp with time zone,
        "CompletedByUserId" uuid,
        "Notes" text NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OffboardingChecklistItemSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "OffboardingChecklistSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "OffboardingId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "Status" text NOT NULL,
        "CompletedAtUtc" timestamp with time zone,
        "CompletedByUserId" uuid,
        "Notes" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OffboardingChecklistSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "OffboardingChecklistTemplateSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "RoleName" text NOT NULL,
        "ItemCode" text NOT NULL,
        "ItemLabel" text NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsRequired" boolean NOT NULL,
        "RequiresApproval" boolean NOT NULL,
        "RequiresEsign" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OffboardingChecklistTemplateSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "OffboardingEsignDocumentSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ChecklistItemId" uuid NOT NULL,
        "DocumentName" text NOT NULL,
        "DocumentUrl" text NOT NULL,
        "Status" text NOT NULL,
        "SignedByUserId" uuid,
        "SignedAtUtc" timestamp with time zone,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_OffboardingEsignDocumentSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "PayrollApprovalActionSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PayrollRunId" uuid NOT NULL,
        "StageCode" text NOT NULL,
        "ActionType" text NOT NULL,
        "ActionStatus" text NOT NULL,
        "ActorUserId" uuid,
        "ActionAtUtc" timestamp with time zone NOT NULL,
        "Reason" text NOT NULL,
        "ReferenceId" text NOT NULL,
        "RolledBackActionId" uuid,
        "MetadataJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollApprovalActionSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "PayrollApprovalMatrixSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "PayrollScope" text NOT NULL,
        "StageCode" text NOT NULL,
        "StageName" text NOT NULL,
        "StageOrder" integer NOT NULL,
        "ApproverRole" text NOT NULL,
        "AllowRollback" boolean NOT NULL,
        "AutoApproveEnabled" boolean NOT NULL,
        "SlaEscalationHours" integer NOT NULL,
        "EscalationRole" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollApprovalMatrixSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "PayrollForecastResultSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ScenarioId" uuid NOT NULL,
        "ForecastYear" integer NOT NULL,
        "ForecastMonth" integer NOT NULL,
        "ProjectedPayrollCost" numeric NOT NULL,
        "ProjectedHeadcount" integer NOT NULL,
        "ProjectedSaudizationPercent" numeric NOT NULL,
        "ComplianceRiskScore" integer NOT NULL,
        "ResultJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollForecastResultSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "PayrollForecastScenarioSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "ScenarioName" text NOT NULL,
        "BasePayrollRunId" uuid,
        "PlannedSaudiHires" integer NOT NULL,
        "PlannedNonSaudiHires" integer NOT NULL,
        "PlannedAttrition" integer NOT NULL,
        "PlannedSalaryDeltaPercent" numeric NOT NULL,
        "AssumptionsJson" text NOT NULL,
        "CreatedByUserId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_PayrollForecastScenarioSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "ShiftRuleSet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "Name" text NOT NULL,
        "StandardDailyHours" numeric NOT NULL,
        "OvertimeMultiplierWeekday" numeric NOT NULL,
        "OvertimeMultiplierWeekend" numeric NOT NULL,
        "OvertimeMultiplierHoliday" numeric NOT NULL,
        "WeekendDaysCsv" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_ShiftRuleSet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE TABLE "TimesheetEntrySet" (
        "Id" uuid NOT NULL,
        "TenantId" uuid NOT NULL,
        "EmployeeId" uuid NOT NULL,
        "ShiftRuleId" uuid,
        "WorkDate" date NOT NULL,
        "HoursWorked" numeric NOT NULL,
        "ApprovedOvertimeHours" numeric NOT NULL,
        "IsWeekend" boolean NOT NULL,
        "IsHoliday" boolean NOT NULL,
        "Status" text NOT NULL,
        "ApprovedByUserId" uuid,
        "ApprovedAtUtc" timestamp with time zone,
        "Notes" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "UpdatedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_TimesheetEntrySet" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeSet_TenantId_GradeCode_LocationCode" ON "EmployeeSet" ("TenantId", "GradeCode", "LocationCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_AllowancePolicyMatrixSet_TenantId_GradeCode_LocationCode_Ef~" ON "AllowancePolicyMatrixSet" ("TenantId", "GradeCode", "LocationCode", "EffectiveFrom");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_AllowancePolicyMatrixSet_TenantId_IsActive_GradeCode_Locati~" ON "AllowancePolicyMatrixSet" ("TenantId", "IsActive", "GradeCode", "LocationCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_AllowancePolicySet_TenantId_IsActive_JobTitle" ON "AllowancePolicySet" ("TenantId", "IsActive", "JobTitle");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_AllowancePolicySet_TenantId_PolicyName" ON "AllowancePolicySet" ("TenantId", "PolicyName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_ComplianceRuleEventSet_TenantId_RuleId_Status" ON "ComplianceRuleEventSet" ("TenantId", "RuleId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_ComplianceRuleEventSet_TenantId_Status_TriggeredAtUtc" ON "ComplianceRuleEventSet" ("TenantId", "Status", "TriggeredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_ComplianceRuleSet_TenantId_RuleCode" ON "ComplianceRuleSet" ("TenantId", "RuleCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_DataQualityFixBatchSet_TenantId_BatchReference" ON "DataQualityFixBatchSet" ("TenantId", "BatchReference");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_DataQualityIssueSet_TenantId_EntityType_EntityId" ON "DataQualityIssueSet" ("TenantId", "EntityType", "EntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_DataQualityIssueSet_TenantId_IssueStatus_Severity_DetectedA~" ON "DataQualityIssueSet" ("TenantId", "IssueStatus", "Severity", "DetectedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeLoanInstallmentSet_TenantId_EmployeeId_Year_Month_S~" ON "EmployeeLoanInstallmentSet" ("TenantId", "EmployeeId", "Year", "Month", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_EmployeeLoanInstallmentSet_TenantId_EmployeeLoanId_Year_Mon~" ON "EmployeeLoanInstallmentSet" ("TenantId", "EmployeeLoanId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeLoanSet_TenantId_EmployeeId_Status" ON "EmployeeLoanSet" ("TenantId", "EmployeeId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeOffboardingSet_TenantId_EmployeeId_CreatedAtUtc" ON "EmployeeOffboardingSet" ("TenantId", "EmployeeId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeOffboardingSet_TenantId_Status_EffectiveDate" ON "EmployeeOffboardingSet" ("TenantId", "Status", "EffectiveDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeSelfServiceRequestSet_TenantId_EmployeeId_RequestTy~" ON "EmployeeSelfServiceRequestSet" ("TenantId", "EmployeeId", "RequestType", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_EmployeeSelfServiceRequestSet_TenantId_Status_CreatedAtUtc" ON "EmployeeSelfServiceRequestSet" ("TenantId", "Status", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_IntegrationSyncJobSet_TenantId_DeadlineAtUtc_Status" ON "IntegrationSyncJobSet" ("TenantId", "DeadlineAtUtc", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_IntegrationSyncJobSet_TenantId_IdempotencyKey" ON "IntegrationSyncJobSet" ("TenantId", "IdempotencyKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_IntegrationSyncJobSet_TenantId_Provider_Status_NextAttemptA~" ON "IntegrationSyncJobSet" ("TenantId", "Provider", "Status", "NextAttemptAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_NotificationQueueSet_TenantId_Channel_Status" ON "NotificationQueueSet" ("TenantId", "Channel", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_NotificationQueueSet_TenantId_Status_ScheduledAtUtc" ON "NotificationQueueSet" ("TenantId", "Status", "ScheduledAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_NotificationTemplateSet_TenantId_TemplateCode_Channel" ON "NotificationTemplateSet" ("TenantId", "TemplateCode", "Channel");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_OffboardingChecklistApprovalSet_TenantId_ChecklistItemId_St~" ON "OffboardingChecklistApprovalSet" ("TenantId", "ChecklistItemId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_OffboardingChecklistItemSet_TenantId_ChecklistId_ItemCode" ON "OffboardingChecklistItemSet" ("TenantId", "ChecklistId", "ItemCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_OffboardingChecklistItemSet_TenantId_ChecklistId_SortOrder" ON "OffboardingChecklistItemSet" ("TenantId", "ChecklistId", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_OffboardingChecklistSet_TenantId_OffboardingId" ON "OffboardingChecklistSet" ("TenantId", "OffboardingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_OffboardingChecklistTemplateSet_TenantId_RoleName_IsActive" ON "OffboardingChecklistTemplateSet" ("TenantId", "RoleName", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_OffboardingChecklistTemplateSet_TenantId_RoleName_ItemCode" ON "OffboardingChecklistTemplateSet" ("TenantId", "RoleName", "ItemCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_OffboardingEsignDocumentSet_TenantId_ChecklistItemId_Status" ON "OffboardingEsignDocumentSet" ("TenantId", "ChecklistItemId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_PayrollApprovalActionSet_TenantId_PayrollRunId_ActionAtUtc" ON "PayrollApprovalActionSet" ("TenantId", "PayrollRunId", "ActionAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_PayrollApprovalActionSet_TenantId_StageCode_ActionStatus" ON "PayrollApprovalActionSet" ("TenantId", "StageCode", "ActionStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_PayrollApprovalMatrixSet_TenantId_PayrollScope_StageCode" ON "PayrollApprovalMatrixSet" ("TenantId", "PayrollScope", "StageCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_PayrollForecastResultSet_TenantId_ScenarioId_ForecastYear_F~" ON "PayrollForecastResultSet" ("TenantId", "ScenarioId", "ForecastYear", "ForecastMonth");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_PayrollForecastScenarioSet_TenantId_CreatedAtUtc" ON "PayrollForecastScenarioSet" ("TenantId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_ShiftRuleSet_TenantId_Name" ON "ShiftRuleSet" ("TenantId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE UNIQUE INDEX "IX_TimesheetEntrySet_TenantId_EmployeeId_WorkDate" ON "TimesheetEntrySet" ("TenantId", "EmployeeId", "WorkDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    CREATE INDEX "IX_TimesheetEntrySet_TenantId_Status_WorkDate" ON "TimesheetEntrySet" ("TenantId", "Status", "WorkDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260227150204_AddEmployeeGradeAndLocationCode') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260227150204_AddEmployeeGradeAndLocationCode', '8.0.12');
    END IF;
END $EF$;
COMMIT;

